"""Definitions for the screening assessments available to users."""

from django.http import Http404


ASSESSMENTS = [
    {
        "id": 1,
        "title": "Breast_Cancer",
        "title_en": "Breast Cancer Risk Assessment",
        "title_fa": "ارزیابی ریسک سرطان سینه",
        "title_ar": "تقييم مخاطر سرطان الثدي",
        "desc_en": "Breast Cancer Risk Assessment",
        "desc_fa": "ارزیابی ریسک سرطان سینه",
        "desc_ar": "تقييم مخاطر سرطان الثدي",
        "image": "breast.png",
        "tags": "سرطان سینه",
        "speciality": 1,
        "groups": ["Female"],
        "active": 1,
    },
    {
        "id": 2,
        "title": "Colorectal_Cancer",
        "title_en": "Colorectal Cancer Risk Assessment",
        "title_fa": "ارزیابی ریسک سرطان کلورکتال",
        "title_ar": "تقييم مخاطر سرطان القولون والمستقيم",
        "desc_en": "Colorectal Cancer Risk Assessment",
        "desc_fa": "ارزیابی ریسک سرطان کلورکتال",
        "desc_ar": "تقييم مخاطر سرطان القولون والمستقيم",
        "image": "colorectal.png",
        "tags": "سرطان کلورکتال",
        "speciality": 1,
        "groups": ["Male", "Female"],
        "active": 1,
    },
    {
        "id": 3,
        "title": "Prostate_Cancer",
        "title_en": "Prostate Cancer Risk Assessment",
        "title_fa": "ارزیابی ریسک سرطان پروستات",
        "title_ar": "تقييم مخاطر سرطان البروستاتا",
        "desc_en": "Prostate Cancer Risk Assessment",
        "desc_fa": "ارزیابی ریسک سرطان پروستات",
        "desc_ar": "تقييم مخاطر سرطان البروستاتا",
        "image": "prostate.png",
        "tags": "سرطان پروستات",
        "speciality": 1,
        "groups": ["Male"],
        "active": 1,
    },
    {
        "id": 4,
        "title": "Cervical_Cancer",
        "title_en": "Cervical Cancer Risk Assessment",
        "title_fa": "ارزیابی ریسک سرطان دهانه رحم",
        "title_ar": "تقييم مخاطر سرطان عنق الرحم",
        "desc_en": "Cervical Cancer Risk Assessment",
        "desc_fa": "ارزیابی ریسک سرطان دهانه رحم",
        "desc_ar": "تقييم مخاطر سرطان عنق الرحم",
        "image": "cervical.png",
        "tags": "سرطان دهانه رحم",
        "speciality": 1,
        "groups": ["Female"],
        "active": 1,
    },
    {
        "id": 5,
        "title": "Diabetes",
        "title_en": "Diabetes Risk Assessment",
        "title_fa": "ارزیابی ریسک دیابت",
        "title_ar": "تقييم مخاطر السكري",
        "desc_en": "Diabetes Risk Assessment",
        "desc_fa": "ارزیابی ریسک دیابت",
        "desc_ar": "تقييم مخاطر السكري",
        "image": "diabetes.png",
        "tags": "دیابت",
        "speciality": 1,
        "groups": ["Male", "Female"],
        "active": 1,
    },
    {
        "id": 6,
        "title": "Cardiovascular_Disease",
        "title_en": "Cardiovascular Disease Risk Assessment",
        "title_fa": "ارزیابی ریسک قلبی-عروقی",
        "title_ar": "تقييم مخاطر أمراض القلب والأوعية الدموية",
        "desc_en": "Cardiovascular Disease Risk Assessment",
        "desc_fa": "ارزیابی ریسک قلبی-عروقی",
        "desc_ar": "تقييم مخاطر أمراض القلب والأوعية الدموية",
        "image": "cardiovasculare.png",
        "tags": "قلبی-عروقی",
        "speciality": 1,
        "groups": ["Male", "Female"],
        "active": 1,
    },
    {
        "id": 7,
        "title": "Melanoma_Cancer",
        "title_en": "Melanoma Cancer Risk Assessment",
        "title_fa": "ارزیابی ریسک سرطان پوست",
        "title_ar": "تقييم مخاطر سرطان الجلد (الميلانوما)",
        "desc_en": "Melanoma Cancer Risk Assessment",
        "desc_fa": "ارزیابی ریسک سرطان پوست",
        "desc_ar": "تقييم مخاطر سرطان الجلد (الميلانوما)",
        "image": "melanoma.png",
        "tags": "سرطان پوست",
        "speciality": 1,
        "groups": ["Male", "Female"],
        "active": 1,
    },
    {
        "id": 8,
        "title": "Osteoporosis",
        "title_en": "Osteoporosis Risk Assessment",
        "title_fa": "ارزیابی ریسک پوکی استخوان",
        "title_ar": "تقييم مخاطر هشاشة العظام",
        "desc_en": "Osteoporosis Risk Assessment",
        "desc_fa": "ارزیابی ریسک پوکی استخوان",
        "desc_ar": "تقييم مخاطر هشاشة العظام",
        "image": "osteoporosis.png",
        "tags": "پوکی استخوان",
        "speciality": 1,
        "groups": ["Male", "Female"],
        "active": 1,
    },
    {
        "id": 9,
        "title": "Ovarian_Cancer",
        "title_en": "Ovarian Cancer Risk Assessment",
        "title_fa": "ارزیابی ریسک سرطان تخمدان",
        "title_ar": "تقييم مخاطر سرطان المبيض",
        "desc_en": "Ovarian Cancer Risk Assessment",
        "desc_fa": "ارزیابی ریسک سرطان تخمدان",
        "desc_ar": "تقييم مخاطر سرطان المبيض",
        "image": "ovarian.png",
        "tags": "سرطان تخمدان",
        "speciality": 1,
        "groups": ["Female"],
        "active": 1,
    },
    {
        "id": 10,
        "title": "Stomach_Cancer",
        "title_en": "Stomach Cancer Risk Assessment",
        "title_fa": "ارزیابی ریسک سرطان معده",
        "title_ar": "تقييم مخاطر سرطان المعدة",
        "desc_en": "Stomach Cancer Risk Assessment",
        "desc_fa": "ارزیابی ریسک سرطان معده",
        "desc_ar": "تقييم مخاطر سرطان المعدة",
        "image": "stomach.png",
        "tags": "سرطان معده",
        "speciality": 1,
        "groups": ["Male", "Female"],
        "active": 1,
    },
    {
        "id": 11,
        "title": "Stroke",
        "title_en": "Stroke Risk Assessment",
        "title_fa": "ارزیابی ریسک سکته مغزی",
        "title_ar": "تقييم مخاطر السكتة الدماغية",
        "desc_en": "Stroke Risk Assessment",
        "desc_fa": "ارزیابی ریسک سکته مغزی",
        "desc_ar": "تقييم مخاطر السكتة الدماغية",
        "image": "stroke.png",
        "tags": "سکته مغزی",
        "speciality": 1,
        "groups": ["Male", "Female"],
        "active": 1,
    },
    {
        "id": 12,
        "title": "Pancreatic_Cancer",
        "title_en": "Pancreatic Cancer Risk Assessment",
        "title_fa": "ارزیابی ریسک سرطان پانکراس",
        "title_ar": "تقييم مخاطر سرطان البنكرياس",
        "desc_en": "Pancreatic Cancer Risk Assessment",
        "desc_fa": "ارزیابی ریسک سرطان پانکراس",
        "desc_ar": "تقييم مخاطر سرطان البنكرياس",
        "image": "pancreatic.png",
        "tags": "سرطان پانکراس",
        "speciality": 1,
        "groups": ["Male", "Female"],
        "active": 1,
    },
]


def get_assessment_or_404(assessment_id):
    """Return an assessment by its public ID or raise a normal 404 response."""
    assessment = next(
        (item for item in ASSESSMENTS if item['id'] == assessment_id),
        None,
    )
    if assessment is None:
        raise Http404('Assessment not found.')
    return assessment
