# Generated by Django 5.2.1 on 2025-07-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_organization_profile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Person', 'Person'), ('Organization', 'Organization')], default='Person', max_length=50, null=True),
        ),
    ]
