# Generated by Django 5.2.1 on 2025-09-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sentence',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
