# Generated by Django 5.2.1 on 2025-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigreejs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='famid',
            field=models.CharField(max_length=50),
        ),
    ]
