# Generated by Django 5.2.1 on 2025-12-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigreejs', '0002_alter_pedigree_code_alter_pedigree_famid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='risk_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
