# Generated by Django 5.2.1 on 2025-06-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('affected', models.CharField(choices=[('H', 'سالم'), ('C', 'مبتلا به سرطان')], max_length=1, verbose_name='وضعیت بیماری')),
                ('cancer_type', models.CharField(blank=True, max_length=100, verbose_name='نوع سرطان')),
                ('age_diagnosis', models.PositiveIntegerField(blank=True, null=True, verbose_name='سن تشخیص سرطان')),
                ('genes', models.CharField(blank=True, max_length=200, verbose_name='ژن\u200cهای جهش\u200cیافته')),
                ('age', models.PositiveIntegerField(verbose_name='سن فعلی یا سن فوت')),
                ('status', models.CharField(choices=[('A', 'زنده'), ('D', 'فوت شده')], max_length=1, verbose_name='وضعیت زنده یا فوت شده')),
                ('parents', models.ManyToManyField(blank=True, to='pedigree.familymember', verbose_name='والدین')),
            ],
            options={
                'verbose_name': 'عضو خانواده',
                'verbose_name_plural': 'اعضای خانواده',
            },
        ),
    ]
