# Generated by Django 5.2.1 on 2025-07-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0002_family_individual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='family',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='father',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='mother',
        ),
        migrations.AddField(
            model_name='familymember',
            name='generation',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
    ]
