# Generated by Django 5.2.1 on 2025-07-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0003_remove_individual_family_remove_individual_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='generation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
