# Generated by Django 5.2.1 on 2025-09-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0004_alter_familymember_generation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'verbose_name': 'FamilyMember', 'verbose_name_plural': 'FamilyMembers'},
        ),
    ]
