# Generated by Django 5.2.1 on 2025-06-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('specialty', models.CharField(blank=True, max_length=200, null=True)),
                ('specialty_en', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('position_en', models.CharField(blank=True, max_length=200, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images/team')),
                ('team_type', models.CharField(blank=True, choices=[('Main', 'Main'), ('Advisor', 'Advisor')], default='Advisor', max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
