# Generated by Django 5.2.1 on 2025-06-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image_center1',
            field=models.ImageField(blank=True, null=True, upload_to='images/center'),
        ),
        migrations.AddField(
            model_name='team',
            name='image_center2',
            field=models.ImageField(blank=True, null=True, upload_to='images/center'),
        ),
        migrations.AddField(
            model_name='team',
            name='image_center3',
            field=models.ImageField(blank=True, null=True, upload_to='images/center'),
        ),
    ]
