# Generated by Django 5.2.1 on 2026-09-22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0001_initial'),
        ('my_model', '0010_validate_uploaded_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupprogram',
            name='assessment_id',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Breast Cancer Risk Assessment'),
                    (2, 'Colorectal Cancer Risk Assessment'),
                    (3, 'Prostate Cancer Risk Assessment'),
                    (4, 'Cervical Cancer Risk Assessment'),
                    (5, 'Diabetes Risk Assessment'),
                    (6, 'Cardiovascular Disease Risk Assessment'),
                    (7, 'Melanoma Cancer Risk Assessment'),
                    (8, 'Osteoporosis Risk Assessment'),
                    (9, 'Ovarian Cancer Risk Assessment'),
                    (10, 'Stomach Cancer Risk Assessment'),
                    (11, 'Stroke Risk Assessment'),
                    (12, 'Pancreatic Cancer Risk Assessment'),
                ],
                help_text='The disease/assessment this follow-up program belongs to.',
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name='followupplan',
            constraint=models.UniqueConstraint(
                fields=('screening', 'program'),
                name='unique_follow_up_plan_per_screening_program',
            ),
        ),
    ]
