# Generated by Django 5.2.1 on 2025-06-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='anticonvulsants',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='blood_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='calcium_supplements',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='cannedfood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='cereal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='chemotherapy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='chronic_pancreatitis',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='colored_eyes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='colored_hair',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='dairy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='endometriosis',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='fair_skin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='family_break_bone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='family_breast_ovarian_prostate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='family_history_stroke',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='family_melanoma_cancer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='family_ovarian_cancer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='family_pancreatic_cancer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='family_stomach_cancer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='fastfood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='h_pylori',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='have_bmd_test',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='history_totchol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='hysterectomy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='immunosuppressive_drugs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='melanoma_cancer_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='menopause',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='menopause_hormone',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='moles_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='osteoporosis_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='ovarian_cancer_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='pancreatic_cancer_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='previous_cancer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='previous_stroke',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='result_bmd_test',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='rheumatoid_arthritis',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='salpingectomy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='steroid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='stomach_cancer_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='stroke_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='sunburns',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='sunlamp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='talcum_powder',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='vitamin_d',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
