# Generated by Django 5.2.1 on 2025-06-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_model', '0002_mymodel_anticonvulsants_mymodel_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='selected_assessments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
