# Generated by Django 5.2.1 on 2025-06-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_model', '0003_mymodel_selected_assessments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='selected_assessments',
            new_name='selected_assessments_title',
        ),
    ]
