# Generated by Django 5.2.1 on 2025-06-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_model', '0004_rename_selected_assessments_mymodel_selected_assessments_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='selected_assessments_title',
            new_name='selected_assessments_id',
        ),
    ]
