# Generated by Django 5.2.1 on 2026-07-15 07:26

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_model', '0006_assessmentgroup_alter_mymodel_code_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='screening_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Complete screening data including all questions and answers', null=True),
        ),
    ]
