# Generated by Django 5.2.1 on 2026-07-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_model', '0007_mymodel_screening_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='screening_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
