# Generated by Django 5.2.1 on 2026-09-20 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_model', '0008_alter_mymodel_screening_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='screening_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mymodel',
            index=models.Index(fields=['userid', '-created'], name='my_model_my_userid__5599a1_idx'),
        ),
        migrations.AddIndex(
            model_name='mymodel',
            index=models.Index(fields=['code', '-created'], name='my_model_my_code_73ab05_idx'),
        ),
    ]
